### ISSUE TITLE
taro编译微信后报错

### ISSUE THREAD

**Issue by sjhleo** [yangger6/mini-lifecycle-interceptor#2]
![image](https://user-images.githubusercontent.com/30336191/145533695-7c9e77b1-0208-4979-8cb2-67b4d4d3ebc8.png)
taro1.3.46编译微信后，控制台报错，编译成支付宝可以正常使用

**Comment by yangger6** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yangger6** [comment]
@sjhleo 麻烦提供一下node版本号和使用的api

**Comment by sjhleo** [comment]
node版本v14.18.1。
![image](https://user-images.githubusercontent.com/30336191/145534861-ce3ee914-1e41-4ba2-8942-1b9e9c7ae955.png)

**Comment by sjhleo** [comment]
> @sjhleo 麻烦提供一下node版本号和使用的api
v14.18.1。使用的api见图

**Comment by sjhleo** [comment]
taro版本是1.3.45 打错了 上面 @yangger6

**Comment by yangger6** [comment]
更新一下0.0.5版本就可以了 @sjhleo

**Comment by yangger6** [comment]
忘记说了，我在测试的时候，taro1.x页面走的是组件的生命周期，拦截器也要用组件的，你可以试试看 @sjhleo

**Comment by sjhleo** [comment]
> 忘记说了，我在测试的时候，taro1.x页面走的是组件的生命周期，拦截器也要用组件的，你可以试试看 @sjhleo

好的 我测试看一看

**Comment by sjhleo** [comment]
> 忘记说了，我在测试的时候，taro1.x页面走的是组件的生命周期，拦截器也要用组件的，你可以试试看 @sjhleo

更新后taro编译没报错了，但是像图上的代码，在支付宝小程序中可以拦截页面的onShow事件，但是在微信里面没有拦截到onShow

**Comment by sjhleo** [comment]
> > 忘记说了，我在测试的时候，taro1.x页面走的是组件的生命周期，拦截器也要用组件的，你可以试试看 @sjhleo
> 
> 更新后taro编译没报错了，但是像图上的代码，在支付宝小程序中可以拦截页面的onShow事件，但是在微信里面没有拦截到onShow

使用组件的show事件监听添加 ，但是提示show.use is not a function，你的意思是使用taro 就无法实现页面生命周期的拦截么，但是图上这种写法在0.0.4的版本使用taro编译后的支付宝小程序是生效的，现在更新到0.
0.5微信无法拦截页面生命周期 @yangger6

**Comment by yangger6** [comment]
@sjhleo taro在1.x版本的时候，微信小程序页面的生命周期是以组件的形式注册成页面的，所以走的是Component的生命周期，这一点我没去深究taro的源码，你试试看组件的生命周期能否捕获到呢？例如created的去拦截

**Comment by sjhleo** [comment]
> 命周期能否捕获到

组件的生命周期created等是可以拦截到的的，但是我希望拦截的是页面的生命周期，0.0.4版本在支付宝版本可以。

**Comment by sjhleo** [comment]
> 0.0.4

我们以前微信有自己实现拦截页面生命周期的hack代码，这次主要是实现支付宝的，然后刚好找到你这个包，于是想统一一下，不是做伸手党哈，不过我现在刚接触小程序，水平还没跟上

**Comment by sjhleo** [comment]
> 的
taro源码我看了，支付宝跟微信的区别是，微信吧页面级别相关的生命周期放到了weappComponentConf的methods对象中，而支付宝是直接定义weappComponentConf对象上，是不是这里的区别导致页面生命周期在支付宝和微信上的不同

**Comment by yangger6** [comment]
是这样，不同的平台taro编译出来的代码是不一样的逻辑，支付宝我刚刚也看了，可以用onLoad，onShow捕获到.
微信和支付宝小程序页面和组件都是通过的Page和Component这两个方法去创建的，在taro1.x的版本，支付宝的`页面`确实是通过Page这个方法去创建的，所以你用onLoad，onShow能捕获到页面的生命周期.
但是微信的`页面`是通过Component这个方法去创建，所以只能用created, attached这些组件的生命周期方法去捕获你的`页面`的生命周期.
你可以验证一下，taro我是2.x开始用的，1.x也不太了解

微信：
![image](https://user-images.githubusercontent.com/23329645/145770058-0dfebd7a-7bcb-43ae-9167-e5f917251677.png)

**Comment by sjhleo** [comment]
> 
```  js
const originalComponent = Component;
const componentInterceptor = () => {
  Component = function (options) {
    mixLifeCycle(options.methods, componentLifeCycle);
    return originalComponent.call(this, options);
  };
};
componentInterceptor ();
```
微信是这样处理的，Component是微信原生的函数，componentLifeCycle里面就是我们需要拦截的页面生命周期方法，比如onShow，是不是可以参考，统一处理下

**Comment by yangger6** [comment]
在我看来，`页面`走Component的生命周期(例如 created，attached)本来就是错的，不管是在原生小程序还是Taro2.x, Taro3.x，`页面`都是走Page的生命周期(例如onLoad，onShow)，对应组件和页面的拦截器，都是用针对的生命周期方法进行拦截，所以这个问题应该是Taro1.x带来的，针对Taro1.x暂时不会做兼容处理.

**Comment by sjhleo** [comment]
> 在我看来，`页面`走Component的生命周期(例如 created，attached)本来就是错的，不管是在原生小程序还是Taro2.x, Taro3.x，`页面`都是走Page的生命周期(例如onLoad，onShow)，对应组件和页面的拦截器，都是用针对的生命周期方法进行拦截，所以这个问题应该是Taro1.x带来的，针对Taro1.x暂时不会做兼容处理.

好的 后续看我们这边是否升级了。微信我还是用我们之前的方式处理了。多谢大佬
